bump msrv (due to clap)
> error: package `clap v4.5.53` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.66.1