bump msrv (due to anstream)
❯ cargo tree --invert anstream
anstream v0.6.21
└── clap_builder v4.5.53
    └── clap v4.5.53
        └── weeks-from-now v0.2.1 (/home/tshepang/repos/weeks-from-now)

> error: package `anstream v0.6.21` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.64.0